[package]
name = "gm8decompiler"
version = "2.0.4"
authors = ["Adamcake", "viri"]
license = "GPL-2.0-only"
edition = "2018"

[build-dependencies]
chrono = "0.4"

[dependencies]
flate2 = "1.0.12"
getopts = "0.2.21"
gm8exe = { path = "gm8exe" }
minio = { git = "https://github.com/notviri/minio" }
rayon = "1.2"

[profile.release]
codegen-units = 1
lto = true
panic = "abort"

[workspace]
members = ["gm8exe"]
